resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
  - vstest

steps:
- task: VSBuild@1
  displayName: Build
  inputs:
    solution: Neteril.ComputationExpression.sln
    msbuildArgs: /restore
    configuration: Release


- task: VSTest@2
  displayName: Test
  inputs:
    testAssemblyVer2: 'Neteril.ComputationExpression.Tests/bin/**/Neteril.ComputationExpression.Tests.dll'


- task: CopyFiles@2
  displayName: 'Copy nupkg'
  inputs:
    SourceFolder: Neteril.ComputationExpression
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish nupkg artifact'
  inputs:
    ArtifactName: NuGet


- task: NuGetCommand@2
  displayName: 'Push nupkg'
  inputs:
    command: push
    publishVstsFeed: 'c65a1505-2d13-4094-bca3-1e5536b7c87b'
